import * as fs from "node:fs/promises";
import { createHash } from "node:crypto";
import * as path from "node:path";
import { containsVersionSentinel, versionSentinelFor } from "../native/version-sentinel.js";

const outputPath = path.join(import.meta.dir, "../native/embedded-addon.js");
const packageJsonPath = path.join(import.meta.dir, "../package.json");
const nativeDir = path.join(import.meta.dir, "../native");
const archivePrefix = "embedded-addons.";
const archiveSuffix = ".tar.gz";

const embeddedAddonTypedefs = `/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {number} size
 * @property {string} sha256
 * @property {string=} filePath
 */

/**
 * @typedef {Object} EmbeddedAddonArchive
 * @property {"tar.gz"} format
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} applicationVersion
 * @property {string} nativeCompatibilityVersion
 * @property {string} payloadSha256
 * @property {EmbeddedAddonFile[]} files
 * @property {EmbeddedAddonArchive=} archive
 */`;

const stubContent = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${embeddedAddonTypedefs}

/** @type {EmbeddedAddon|null} */
export const embeddedAddon = null;
`;
async function resetEmbeddedAddon(): Promise<void> {
	await Bun.write(outputPath, stubContent);
	try {
		const entries = await fs.readdir(nativeDir);
		await Promise.all(
			entries
				.filter(entry => entry.startsWith(archivePrefix) && entry.endsWith(archiveSuffix))
				.map(entry => fs.unlink(path.join(nativeDir, entry))),
		);
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
}

interface CandidateAddon {
	variant: "modern" | "baseline" | "default";
	filename: string;
}

interface AvailableAddon extends CandidateAddon {
	size: number;
	sha256: string;
}

/**
 * Validate and embed native addons for one standalone-binary target.
 */
export async function embedNativeAddon({
	targetPlatform,
	targetArch,
	nativeDir,
	outputPath,
	applicationVersion,
	nativeCompatibilityVersion,
}: {
	targetPlatform: string;
	targetArch: string;
	nativeDir: string;
	outputPath: string;
	applicationVersion: string;
	nativeCompatibilityVersion: string;
}): Promise<void> {
	const platformTag = `${targetPlatform}-${targetArch}`;
	const candidates: CandidateAddon[] =
		targetArch === "x64"
			? [
					{ variant: "modern", filename: `pi_natives.${platformTag}-modern.node` },
					{ variant: "baseline", filename: `pi_natives.${platformTag}-baseline.node` },
				]
			: [{ variant: "default", filename: `pi_natives.${platformTag}.node` }];

	const versionSentinel = versionSentinelFor(nativeCompatibilityVersion);
	const archiveEntries: Record<string, Uint8Array> = {};
	const available: AvailableAddon[] = [];
	for (const candidate of candidates) {
		const candidatePath = path.join(nativeDir, candidate.filename);
		try {
			const bytes = await fs.readFile(candidatePath);
			if (!containsVersionSentinel(bytes, versionSentinel)) {
				throw new Error(
					`Native addon ${candidatePath} does not contain native compatibility ${nativeCompatibilityVersion} sentinel ` +
						`\`${versionSentinel}\`. Rebuild it or provide a matching validated native artifact before embedding.`,
				);
			}
			available.push({
				...candidate,
				size: bytes.length,
				sha256: createHash("sha256").update(bytes).digest("hex"),
			});
			archiveEntries[candidate.filename] = bytes;
		} catch (err) {
			if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
		}
	}

	if (available.length === 0) {
		const expected = candidates.map(candidate => `  - ${candidate.filename}`).join("\n");
		throw new Error(`No native addons found for ${platformTag}. Expected one of:\n${expected}`);
	}

	const archiveFilename = `${archivePrefix}${platformTag}${archiveSuffix}`;
	const archivePath = path.join(nativeDir, archiveFilename);
	const archiveBytes = await new Bun.Archive(archiveEntries, { compress: "gzip", level: 9 }).bytes();
	const payloadSha256 = createHash("sha256").update(archiveBytes).digest("hex");
	await Bun.write(archivePath, archiveBytes);

	const files = available
		.map(
			addon =>
				`\t\t{ variant: ${JSON.stringify(addon.variant)}, filename: ${JSON.stringify(addon.filename)}, size: ${addon.size}, sha256: ${JSON.stringify(addon.sha256)} },`,
		)
		.join("\n");

	const content = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${embeddedAddonTypedefs}

import archivePath from ${JSON.stringify(`../native/${archiveFilename}`)} with { type: "file" };

export const embeddedAddon = {
\tplatformTag: ${JSON.stringify(platformTag)},
\tapplicationVersion: ${JSON.stringify(applicationVersion)},
\tnativeCompatibilityVersion: ${JSON.stringify(nativeCompatibilityVersion)},
\tpayloadSha256: ${JSON.stringify(payloadSha256)},
\tarchive: {
\t\tformat: "tar.gz",
\t\tfilename: ${JSON.stringify(archiveFilename)},
\t\tfilePath: archivePath,
\t},
\tfiles: [
${files}
\t],
};
`;

	await Bun.write(outputPath, content);
}

async function main(): Promise<void> {
	if (process.argv.includes("--reset")) {
		await resetEmbeddedAddon();
		return;
	}

	const packageJson = (await Bun.file(packageJsonPath).json()) as {
		version: string;
		nativeCompatibilityVersion: string;
	};
	await embedNativeAddon({
		targetPlatform: Bun.env.TARGET_PLATFORM || process.platform,
		targetArch: Bun.env.TARGET_ARCH || process.arch,
		nativeDir,
		outputPath,
		applicationVersion: packageJson.version,
		nativeCompatibilityVersion: packageJson.nativeCompatibilityVersion,
	});
}

if (import.meta.main) {
	await main();
}
